### ISSUE TITLE
Can't catch and can't explore

### ISSUE THREAD

**Issue by SparklinStar** [shahank42/poketext#1]
On giving the commands catch and explore, the following error happens

panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/shahank42/poketext/internal/repl.Init.func6({0xc00002a110?, 0xc000024a20?, 0xc00000a1f4?})
        C:/repos/poketext/internal/repl/repl.go:63 +0x3c
main.main()
        C:/repos/poketext/main.go:29 +0x1c2

![image](https://github.com/shahank42/poketext/assets/105942415/91b4f5f7-09bb-4ba3-b828-6e43be615333)

**Comment by shahank42** [comment]
Sorry my bad, I should've been clearer with the instructions.

Here's how you would use the application:

- `map` and `mapb` commands to move through the list of areas (no arguments)
- `explore <area-name>` to see the available Pokemon in an area
- `catch <pokemon-name>` to catch a particular Pokemon
- `inspect <pokemon-name>` to inspect an already caught Pokemon
- `pokedex` to view your caught pokemon

It's basically an error handling problem, and I need to add the argument info to the help as well.
